# Generated by Django 2.1 on 2018-08-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billingAddress',
            new_name='billingAddress1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='emailAddress',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shippingAddress',
            new_name='shippingAddress1',
        ),
    ]
